version: "3.1"

services:
  app-order:
    container_name: service-order-app
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: satellite-images
    networks:
      - service-order
    volumes:
      - ../:/usr/share/app
      - ./config/php.ini/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    environment:
      - ENVIRONMENT=development

  nginx-order:
    container_name: service-order-nginx
    image: nginx
    env_file:
      - ../.env
    restart: always
    networks:
      - service-order
    links:
      - app-order
    depends_on:
      - app-order
    ports:
      - "8082:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/servers:/etc/nginx/servers
      - ./keys/nginx:/keys
      - ../:/usr/share/app

networks:
  service-order: {}
